
DATABASE_HOST: 127.0.0.1
DATABASE_NAME: TodoDB
DATABASE_USER: brad
DATABASE_PASSWORD: kK4fVoGMtzj7TUXrGXat

spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:3306/${DATABASE_NAME}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: create
  flyway:
    url: jdbc:mysql://${DATABASE_HOST}:3306/${DATABASE_NAME}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    encoding: UTF-8
    baseline-on-migrate: true
    enabled: true
  profiles:
    config:
      activate:
        on-profile: dev
server:
  tomcat:
    uri-encoding: UTF-8
    relaxed-query-chars: [ '{','}','[',']','^','<', '>', '|' ]
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true